{
 "title": "Clients (Patterned) Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values with key = \"host\""
   },
   {
    "name": "mvpn",
    "label": "Message VPN",
    "query": "show tag values with key = \"mvpn\" where host=~/$host$/"
   },
   {
    "name": "clientprefix",
    "label": "Client Prefix",
    "query": "show tag values with key = \"clientprefix\" where host=~/$host$/ and mvpn=~/$mvpn$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "mvpn",
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Counts for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clientprefix",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "clientprefix",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "client-p-client-control-bytes-received",
       "query": "SELECT count(\"value\") FROM \"client-p-current-egress-byte-rate-per-second\" WHERE (\"host\" = '$host' AND \"mvpn\" = '$mvpn' AND \"clientprefix\" = '$clientprefix') AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
        { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "mvpn"
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Throughput for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Ingress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Bytes for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-bytes-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "repeat": "mvpn"
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Client Message Rate for VPN $mvpn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 }
  },
  {
   "title": "Ingress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-received",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "Control Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-control-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "alias": "Data Messages for $tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-client-data-messages-sent",
     "query": "SELECT sum(\"value\") FROM \"client-p-current-ingress-byte-rate-per-second\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/ AND \"clientprefix\" =~ /^$clientprefix$/) AND $timeFilter GROUP BY time($interval), \"clientprefix\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  { "title": "Egress Discard Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 } },
  {
   "title": "Total Egress Count for client prefixed with $clientprefix",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-total-egress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Egress Count Change Rate (per second) for client prefixed with $clientprefix",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-total-egress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Discard Reasons Decomposition",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 209 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-transmit-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-message-elided",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-compression-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-client-not-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-payload-could-not-be-formatted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-message-promotion-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "clientprefix" ], "type": "tag" }
     ],
     "measurement": "client-p-ediscard-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" },
      { "condition": "AND", "key": "clientprefix", "operator": "=~", "value": "/^$clientprefix$/" }
     ]
    }
   ]
  }
 ]
}