{
 "title": "InfluxDB Performance",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Key Performance Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average DB Query Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "SELECT \"queryDurationNs\" / \"queriesExecuted\" FROM \"monitor\".\"queryExecutor\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       { "params": [ "/" ], "type": "math" }
      ],
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       { "params": [ "/" ], "type": "math" }
      ]
     ],
     "slimit": "1"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "SELECT \"reqDurationNs\" / \"req\" FROM \"httpd\"",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Runtime Heap Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapAlloc" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapSys" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "MB" }
   ],
   "targets": [
    {
     "alias": "influx-0 $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap active" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap idle" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Data Caching Composition",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": 10,
     "measurement": "tsm1_cache",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "diskBytes" ], "type": "alias" }
      ],
      [
       { "params": [ "memBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "memBytes" ], "type": "alias" }
      ],
      [
       { "params": [ "cachedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cachedBytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"clientError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Server Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"serverError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Point Intake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}