{
 "title": "Interface Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values from \"interface-rx-bytes\" with key=\"host\""
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "show tag values from \"interface-rx-bytes\" with key=\"intf\" where host='$host'"
   }
  ]
 },
 "panels": [
  {
   "title": "Interface RX Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "intf" ], "type": "tag" }
     ],
     "measurement": "interface-rx-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "intf", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface TX Byte Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "intf" ], "type": "tag" }
     ],
     "measurement": "interface-tx-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "intf", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface RX Packet Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "intf" ], "type": "tag" }
     ],
     "measurement": "interface-rx-pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "intf", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface TX Packet Rate (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "intf" ], "type": "tag" }
     ],
     "measurement": "interface-tx-pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "intf", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  }
 ]
}