{
 "title": "Issues Count View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"solace_hostname.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Entry Count for ${hostname}",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type: \"event\" AND solace_hostname: ${hostname}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Entry Count Over Time for ${hostname}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type: \"event\" AND solace_hostname: ${hostname}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Type Breakdown",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "solace_event_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type: \"event\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Issues Count Over Time for ${hostname}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "warning",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"warning\" AND type: \"event\" AND solace_hostname: ${hostname}",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"error\" AND type: \"event\" AND solace_hostname: ${hostname}",
     "timeField": "@timestamp"
    },
    {
     "alias": "critical",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"critical\" AND type: \"event\" AND solace_hostname: ${hostname}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}