{
 "title": "Operator View",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values from \"router-current-egress-byte-rate-per-second\" with key=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Key Health Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Alerts",
     "type": "alertlist",
     "description": "Investigate those marked as 'Alerting'",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 }
    }
   ]
  },
  { "title": "At a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "content": "## solace1\n\n\n\n",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-redundancy-status",
     "select": [
      [
       { "params": [ "primaryAct" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "content": "## solace2\n\n\n\n",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-redundancy-status",
     "select": [
      [
       { "params": [ "primaryAct" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Warning (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"warning\" AND type: \"event\" AND solace_hostname: \"solace1\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"error\" AND type: \"event\" AND solace_hostname: \"solace1\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Critical (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"critical\" AND type: \"event\" AND solace_hostname: \"solace1\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warning (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"warning\" AND type: \"event\" AND solace_hostname: \"solace2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"error\" AND type: \"event\" AND solace_hostname: \"solace2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Critical (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity: \"critical\" AND type: \"event\" AND solace_hostname: \"solace2\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingress Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-current-ingress-byte-rate-per-second",
     "query": "SELECT \"value\" * 8 FROM \"router-current-ingress-byte-rate-per-second\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Egress Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "router-current-egress-byte-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Client Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-total-clients-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-current-ingress-byte-rate-per-second",
     "query": "SELECT \"value\" * 8 FROM \"router-current-ingress-byte-rate-per-second\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace2" }
     ]
    }
   ]
  },
  {
   "title": "Egress Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "router-current-egress-byte-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace2" }
     ]
    }
   ]
  },
  {
   "title": "Client Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "limit": "1",
     "measurement": "router-total-clients-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace2" }
     ]
    }
   ]
  },
  {
   "title": "Ingress and Egress Byte Rate for All Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Ingress Rate for $host",
   "type": "graph",
   "description": "As alert only works on Graphs and query does not support template, need to create these for alerting.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "router-total-client-bytes-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Egress Rate for $host",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "router-total-client-bytes-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingress and Egress Rate Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Ingress Rate solace1",
   "type": "graph",
   "description": "As alert only works on Graphs and query does not support template, need to create these for alerting.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "solace1",
     "measurement": "router-total-client-bytes-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Egress Rate solace1",
   "type": "graph",
   "description": "As alert only works on Graphs and query does not support template, need to create these for alerting.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "solace1",
     "measurement": "router-total-client-bytes-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace1" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Rate solace2",
   "type": "graph",
   "description": "As alert only works on Graphs and query does not support template, need to create these for alerting.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "solace2",
     "measurement": "router-total-client-bytes-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace2" }
     ]
    }
   ]
  },
  {
   "title": "Egress Rate solace2",
   "type": "graph",
   "description": "As alert only works on Graphs and query does not support template, need to create these for alerting.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "solace2",
     "measurement": "router-total-client-bytes-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "solace2" }
     ]
    }
   ]
  }
 ]
}