{
 "title": "SolCache Level  Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values from \"cacheinstance-total-memory-utilization\" with key=\"host\""
   },
   {
    "name": "mvpn",
    "label": "Message VPN",
    "query": "show tag values from \"cacheinstance-total-memory-utilization\" with key=\"mvpn\" where host='$host'"
   },
   {
    "name": "cacheinstance",
    "label": "SolCache Instance",
    "query": "show tag values from \"cacheinstance-total-memory-utilization\" with key=\"cacheinstance\" where host='$host' and mvpn='$mvpn'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "# SolCache Cluster",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "# SolCache Instance",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SolCache Distributed Cache Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Number of Clusters Configured",
     "limit": "1",
     "measurement": "cachecluster-num-clusters-configured",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Number of Clusters UP",
     "limit": "1",
     "measurement": "cachecluster-num-clusters-up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Number of Instance Configured",
     "limit": "1",
     "measurement": "cachecluster-num-instances-configured",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Number of Instance UP",
     "limit": "1",
     "measurement": "cachecluster-num-instances-up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Admin Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "limit": "1",
     "measurement": "cacheinstance-admin-status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Operational Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "limit": "1",
     "measurement": "cacheinstance-oper-status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Lost Message",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "limit": "1",
     "measurement": "cacheinstance-lost-message",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming Data Msg per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Incoming Data Msg (1 sec sample) (msgs/s)",
     "measurement": "cacheinstance-Incoming-Data-Msg-(1-sec-sample)-(msgs/s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Data Msg per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Outgoing Data Msg (1 sec sample) (msgs/s)",
     "measurement": "cacheinstance-Outgoing-Data-Msg-(1-sec-sample)-(msgs/s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming Data Byte per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Incoming Data Byte (1 sec sample) (bytes/s)",
     "measurement": "cacheinstance-Incoming-Data-Byte-(1-sec-sample)-(bytes/s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Request per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cache Request (1 sec sample) (msgs/s)",
     "measurement": "cacheinstance-Cache-Request-(1-sec-sample)-(msgs/s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Total Memory Utilization",
     "measurement": "cacheinstance-total-memory-utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU Utilization",
     "measurement": "cacheinstance-cpu-utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Message Breakdown",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "alias": "Cluster-Sync Fail",
     "limit": "1",
     "measurement": "cacheinstance-Cluster-Sync-Fail-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Cluster-Sync Suspect",
     "limit": "1",
     "measurement": "cacheinstance-Cluster-Sync-Suspect-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Max Memory",
     "limit": "1",
     "measurement": "cacheinstance-Max-Memory-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Parse Error",
     "limit": "1",
     "measurement": "cacheinstance-Parse-Error-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Max Topics",
     "limit": "1",
     "measurement": "cacheinstance-Max-Topics-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Bytes Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message Bytes Cached",
     "measurement": "cacheinstance-Message-Bytes-Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Messages Cached",
     "measurement": "cacheinstance-Messages-Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Message Breakdown 2",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "alias": "Message Too Big Error",
     "limit": "1",
     "measurement": "cacheinstance-Too-Big-Error-(lost-message)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "P2P Topic Filter",
     "limit": "1",
     "measurement": "cacheinstance-P2P-Topic-Filter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cacheinstance", "operator": "=~", "value": "/^$cacheinstance$/" }
     ]
    }
   ]
  }
 ]
}