{
 "title": "Spool Stats - VPN Level",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"mvpn-spool-current-egress-byte-rate-per-second\" with key=host"
   },
   {
    "name": "mvpn",
    "label": "Message VPN",
    "query": "show tag values from \"mvpn-spool-current-egress-byte-rate-per-second\" with key=mvpn where host=~/$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Message Spool Status for Router $host",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Config Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "configStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Operation Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "operStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Sync Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "syncStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Spool Sync Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "spoolSyncStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Data Path Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "dataPathStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Spool Usage for Message VPN $mvpn for Router $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Message Spool Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-spool-usage-mb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Spooled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-messages-spooled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress/ Egress Rates for Message VPN $mvpn of Router $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Ingress Byte Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-ingress-byte-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-egress-byte-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Message Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-ingress-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Message Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mvpn-spool-current-egress-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Discard Statistics for Message VPN $mvpn or Router $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Discard Reasons",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "Duplicated Messages",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-duplicate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Errored Messages",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-errored-message",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Max Msg Size Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-max-msg-size-exceeded",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Max Msg Usage Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-max-msg-usage-exceeded",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "No Destination",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-nodest",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Out of Order",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-ooo",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Endpoint Quota Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-qendpt-over-quota",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Queue Not Found",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-queue-not-found",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Spool Files Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-spool-file-limit-exceeded",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Spool Over Quota",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-spool-over-quota",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Spool To ADB Failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-spool-to-adb-fail",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Spool To Disk Failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-spool-to-disk-fail",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Spooling Not Ready",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-discard-spooling-not-ready",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "ACL Denied",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-publish-acl-denied",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "SMF TTL Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-smf-ttl-exceeded",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "User Profile Denied Sending GM",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-ingress-user-profile-deny-guaranteed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      }
     ]
    },
    {
     "title": "Egress Discard Reasons",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "Total Deleted",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-total-deleted-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Max Redelivery Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-max-redelivery-exceeded-discard-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Max Redelivery Exceeded to DMQ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-max-redelivery-exceeded-to-dmq-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "Max Redelivery Exceeded to DMQ Failures",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-max-redelivery-exceeded-to-dmq-failures",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "TTL Exceeded",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-total-ttl-exceeded-discard-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "TTL Expired",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-total-ttl-expired-discard-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "TTL Expired to DMQ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-total-ttl-expired-to-dmq-messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      },
      {
       "alias": "TTL Expired to DMQ Failures",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "mvpn" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mvpn-spool-egress-total-ttl-expired-to-dmq-failures",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}