{
 "title": "Spool Stats - Router Level",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"router-message-spool-status\" with key=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Message Spool Status",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Config Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "configStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Operation Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "operStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Sync Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "syncStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Spool Sync Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "spoolSyncStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Data Path Status",
     "limit": "1",
     "measurement": "router-message-spool-status",
     "select": [
      [
       { "params": [ "dataPathStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Message Spool Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "router-message-spool-current-persist-usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Spool Usage Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "ADB",
     "limit": "1",
     "measurement": "router-message-spool-current-rfad-usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Disk",
     "limit": "1",
     "measurement": "router-message-spool-current-disk-usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Spool Files Quota Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "router-message-spool-file-total-used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Spool File Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "Total Available",
     "limit": "1",
     "measurement": "router-message-spool-file-total-available",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Used",
     "limit": "1",
     "measurement": "router-message-spool-file-total-used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Pending Delete",
     "limit": "1",
     "measurement": "router-message-spool-file-total-pending-delete",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Used Percentage",
     "limit": "1",
     "measurement": "router-message-spool-file-total-used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Partition Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Host: $tag_host, Patition: $tag_dpartition",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "dpartition" ], "type": "tag" }
     ],
     "measurement": "router-message-spool-disk-use",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}