{
 "title": "VPN Level Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "show tag values from \"mvpn-client-data-bytes-received\" with key = \"host\""
   },
   {
    "name": "mvpn",
    "label": "Message VPN",
    "query": "show tag values from \"mvpn-client-data-bytes-received\" with key = \"mvpn\" where host='$host'"
   }
  ]
 },
 "panels": [
  {
   "title": "Client Connection Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Client Connections",
     "measurement": "mvpn-connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Total MQTT Clients",
     "measurement": "mvpn-connections-service-mqtt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Total SMF Clients",
     "measurement": "mvpn-connections-service-smf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Total Web Clients",
     "measurement": "mvpn-connections-service-web",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Byte Rate per Second (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes",
     "measurement": "mvpn-client-control-bytes-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Data Bytes",
     "measurement": "mvpn-client-data-bytes-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Byte Rate per Second (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Control Bytes",
     "measurement": "mvpn-client-control-bytes-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Data Bytes",
     "measurement": "mvpn-client-data-bytes-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Rate per Second (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Control Messages",
     "measurement": "mvpn-client-control-messages-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Data Messages",
     "measurement": "mvpn-client-data-messages-received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Rate per Second (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Control Messages",
     "measurement": "mvpn-client-control-messages-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Data Messages",
     "measurement": "mvpn-client-data-messages-sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Compressed Rate per Second (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "mvpn-current-ingress-compressed-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Compressed Rate per Second (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "mvpn-current-egress-compressed-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Discards (VPN Level)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "alias": "Total Ingress Discards",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-total-ingress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Spool Congestion",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Spool Discards",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-msg-spool-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Too Big",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-msg-too-big",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "No Subscription Match",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-no-subscription-match",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Publish Topic ACL",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-publish-topic-acl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "TTL Exceeded",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Topic Parse Error",
     "limit": "1",
     "measurement": "mvpn-ingress-discards-topic-parse-error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Uncompressed Rate per Second (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mvpn-current-ingress-uncompressed-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Uncompressed Rate per Second (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mvpn-current-egress-uncompressed-rate-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Discards (VPN Level)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "alias": "Total Egress Discards",
     "limit": "1",
     "measurement": "mvpn-egress-discards-total-egress-discards",
     "query": "SELECT \"value\" FROM \"mvpn-egress-discards-total-egress-discards\" WHERE (\"host\" =~ /^$host$/ AND \"mvpn\" =~ /^$mvpn$/) AND $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Compression Congestion",
     "limit": "1",
     "measurement": "mvpn-egress-discards-compression-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Elided",
     "limit": "1",
     "measurement": "mvpn-egress-discards-message-elided",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Spool Congestion",
     "limit": "1",
     "measurement": "mvpn-egress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Transmit Congestions",
     "limit": "1",
     "measurement": "mvpn-egress-discards-transmit-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "TTL Exceeded",
     "limit": "1",
     "measurement": "mvpn-egress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Clients Not Connected",
     "limit": "1",
     "measurement": "mvpn-egress-discards-client-not-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Compression Ratio (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mvpn-ingress-compression-ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Compression Ratio (VPN)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mvpn-egress-compression-ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Subscription Break Down (VPN)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mvpn-total-local-unique-subscriptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "measurement": "mvpn-total-remote-unique-subscriptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "measurement": "mvpn-total-unique-subscriptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  }
 ]
}