#!/bin/bash

# This script should be installed on all the linux system that forms the capitalmon system.
#
# It takes the realtime interface TX/RX values and post them to influxdb.
#
# The rationale is to give an approximation of the TX and RX traffic generated by capitalmon.
# Since the allocated servers are dedicated to the use of capitalmon, monitoring by port level is 
# not necessary.  
#
# The script requires the password file generated via gpg.
#
# To run manually:
#
#   nohup ./interfacestat.sh > /dev/null 2>&1 & 
#
#
# interfacestat.sh can also be started and ended by the start.sh and stop.sh.
#

# INPUT
#
interfaceHost=`uname -n`
sleeptime=10    # sleep for 10s
#



# DO NOT MODIFY BELOW

configdir=config
. ${configdir}/system.config

writeToDB () {
  httpcode=`curl -u $dbuser:$PASSWORD -w "%{http_code}" --silent --output /dev/null -i -XPOST "http://$dbhost/write?db=$db" --data-binary @$1`
  returncode=$?
  if [ "$returncode" == "0" ]
  then
    if [ $httpcode -ge 300 ]; then echo `date` "WARN: Error writing to DB with HTTP return code: $httpcode"; cat $1; fi
  else
    echo `date` "ERROR: Non zero curl return code"
  fi
}

while true
do

  rx=`ifconfig | grep $NETIF -A 7 | grep "RX packets" | awk '{print $5}'`
  tx=`ifconfig | grep $NETIF -A 7 | grep "TX packets" | awk '{print $5}'`

  echo "interface_rx,interfacehost=$interfaceHost value=$rx"  > interface_rx
  echo "interface_tx,interfacehost=$interfaceHost value=$tx"  > interface_tx

  writeToDB interface_rx
  writeToDB interface_tx

  rm interface_rx
  rm interface_tx

  sleep $sleeptime

done
