#/bin/bash

# Corresponds to start.sh and kills all processes started by start.sh as well as remove any supporting files generated by pollrouter.sh

PID_FILE=./pid.file

if [ -x /usr/bin/rm ]; then
  RM=/usr/bin/rm
else
  RM=/bin/rm
fi
PKILL=/usr/bin/pkill

$PKILL -f pollrouter
$PKILL -f postdb
$PKILL -f interfacestat
$PKILL -f hostresources
$PKILL -f queueprogress
#$PKILL -f alertWebHook
#$PKILL -f postAlertToTEC
#$PKILL -f nc
$PKILL -f node
$PKILL -f pingrouter
$PKILL -f compress

$RM -fv cn.*
$RM -fv query.*
$RM -fv clientcmdlist.*
$RM -fv insert.*
$RM -fv bcn.*
$RM -fv cachecmdlist.*
$RM -fv bridgecmdlist.*
$RM -fv clientpatterncmdlist.*
$RM -fv mvpncmdlist.*
$RM -fv cmdlist.*
$RM -fv alert.*
$RM -fv mvpnn.*
$RM -fv nmvpnn.*
$RM -fv clientprefixn.*
$RM -fv nclientprefixn.*
$RM -fv $PID_FILE
$RM -fv in.*
$RM -fv bin.*
$RM -fv interfacecmdlist.*
$RM -fv host_cpu_*
$RM -fv host_fs_*
$RM -fv host_mem_*
