{
 "title": "Egress Discard Analysis - Message VPN Level - Bar Charts",
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=host"
   },
   {
    "name": "mvpn",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=mvpn where host=~/$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Egress Discards Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Clients not connected",
     "limit": "1",
     "measurement": "mvpn-egress-discards-client-not-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Compression congrestion",
     "limit": "1",
     "measurement": "mvpn-egress-discards-compression-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Messages Elided",
     "limit": "1",
     "measurement": "mvpn-egress-discards-message-elided",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Message Spool Congestion",
     "limit": "1",
     "measurement": "mvpn-egress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "Transmit Congestion",
     "limit": "1",
     "measurement": "mvpn-egress-discards-transmit-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    },
    {
     "alias": "TTL Exceeded",
     "limit": "1",
     "measurement": "mvpn-egress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Discards for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-total-egress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Compression Congression for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Compression Congestion",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-compression-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Elided for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Messages Elided",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-message-elided",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Transmit Congestion for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transmit Congestion",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-transmit-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Spool Congestion for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message Spool Congestion",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Not Connected for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Client Not Connected",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-client-not-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "TTL Exceeded for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TTL Exceeded",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mvpn-egress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  }
 ]
}