{
 "title": "Egress Discard Analysis - Message VPN Level",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=host"
   },
   {
    "name": "mvpn",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=mvpn where host=~/$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Discards (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-total-egress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Compression Congression (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-compression-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Transmit Congestion (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-transmit-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Not Connected (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-client-not-connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Elided (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-message-elided",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "TTL Exceeded (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Spool Congestion (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-egress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  }
 ]
}