{
 "title": "Ingress Discard Analysis - Message VPN Level",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=host"
   },
   {
    "name": "mvpn",
    "query": "show tag values from \"mvpn-ingress-discards-total-ingress-discards\" with key=mvpn where host=~/$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Discards (per sec)  for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-total-ingress-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Too Big (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-msg-too-big",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "No Subscription Match (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-no-subscription-match",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Publish Topic ACL (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-publish-topic-acl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Topic Parse Error (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-topic-parse-error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "TTL Exceeded (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-ttl-exceeded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Spool Congestion (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-message-spool-congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Spool Discards (per sec) for Router $host, VPN $mvpn (Stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Message VPN: $tag_mvpn",
     "groupBy": [
      { "params": [ "mvpn" ], "type": "tag" }
     ],
     "measurement": "mvpn-ingress-discards-msg-spool-discards",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "mvpn", "operator": "=~", "value": "/^$mvpn$/" }
     ]
    }
   ]
  }
 ]
}