//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 04:30:34 PM BST 
//


package com.solace.psg.enterprisestats.statspump.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="run-configurations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="run-configuration" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="run-on-primary-when-active-standby" type="{}run-condition"/>
 *                             &lt;element name="run-on-backup-when-active-standby" type="{}run-condition"/>
 *                             &lt;element name="run-on-primary-when-active-active" type="{}run-condition"/>
 *                             &lt;element name="run-on-backup-when-active-active" type="{}run-condition"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pollers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="system-poller" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="semp-request" type="{}semp-request-type"/>
 *                             &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="destination" type="{}destination-type"/>
 *                             &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
 *                             &lt;element name="send-empty-message" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                             &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="vpn-poller" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="semp-request" type="{}semp-request-type"/>
 *                             &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="destination" type="{}destination-type"/>
 *                             &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vpn-name-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
 *                             &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="per-vpn-poller" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="semp-request" type="{}semp-request-type"/>
 *                             &lt;element name="is-grouped" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                             &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="destination" type="{}destination-type"/>
 *                             &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
 *                             &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runConfigurations",
    "pollers"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(name = "run-configurations", required = true)
    protected Config.RunConfigurations runConfigurations;
    @XmlElement(required = true)
    protected Config.Pollers pollers;

    /**
     * Gets the value of the runConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link Config.RunConfigurations }
     *     
     */
    public Config.RunConfigurations getRunConfigurations() {
        return runConfigurations;
    }

    /**
     * Sets the value of the runConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.RunConfigurations }
     *     
     */
    public void setRunConfigurations(Config.RunConfigurations value) {
        this.runConfigurations = value;
    }

    /**
     * Gets the value of the pollers property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Pollers }
     *     
     */
    public Config.Pollers getPollers() {
        return pollers;
    }

    /**
     * Sets the value of the pollers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Pollers }
     *     
     */
    public void setPollers(Config.Pollers value) {
        this.pollers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="system-poller" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="semp-request" type="{}semp-request-type"/>
     *                   &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="destination" type="{}destination-type"/>
     *                   &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
     *                   &lt;element name="send-empty-message" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                   &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="vpn-poller" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="semp-request" type="{}semp-request-type"/>
     *                   &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="destination" type="{}destination-type"/>
     *                   &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vpn-name-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
     *                   &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="per-vpn-poller" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="semp-request" type="{}semp-request-type"/>
     *                   &lt;element name="is-grouped" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                   &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="destination" type="{}destination-type"/>
     *                   &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
     *                   &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemPoller",
        "vpnPoller",
        "perVpnPoller"
    })
    public static class Pollers {

        @XmlElement(name = "system-poller")
        protected List<Config.Pollers.SystemPoller> systemPoller;
        @XmlElement(name = "vpn-poller")
        protected List<Config.Pollers.VpnPoller> vpnPoller;
        @XmlElement(name = "per-vpn-poller")
        protected List<Config.Pollers.PerVpnPoller> perVpnPoller;

        /**
         * Gets the value of the systemPoller property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemPoller property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystemPoller().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.Pollers.SystemPoller }
         * 
         * 
         */
        public List<Config.Pollers.SystemPoller> getSystemPoller() {
            if (systemPoller == null) {
                systemPoller = new ArrayList<Config.Pollers.SystemPoller>();
            }
            return this.systemPoller;
        }

        /**
         * Gets the value of the vpnPoller property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vpnPoller property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVpnPoller().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.Pollers.VpnPoller }
         * 
         * 
         */
        public List<Config.Pollers.VpnPoller> getVpnPoller() {
            if (vpnPoller == null) {
                vpnPoller = new ArrayList<Config.Pollers.VpnPoller>();
            }
            return this.vpnPoller;
        }

        /**
         * Gets the value of the perVpnPoller property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the perVpnPoller property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPerVpnPoller().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.Pollers.PerVpnPoller }
         * 
         * 
         */
        public List<Config.Pollers.PerVpnPoller> getPerVpnPoller() {
            if (perVpnPoller == null) {
                perVpnPoller = new ArrayList<Config.Pollers.PerVpnPoller>();
            }
            return this.perVpnPoller;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="semp-request" type="{}semp-request-type"/>
         *         &lt;element name="is-grouped" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *         &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="destination" type="{}destination-type"/>
         *         &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
         *         &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "description",
            "sempRequest",
            "isGrouped",
            "runConfiguration",
            "destination",
            "topicStringSuffix",
            "baseTag",
            "objectTags",
            "minSempVer",
            "maxSempVer",
            "minPollIntervalSec"
        })
        public static class PerVpnPoller {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "semp-request", required = true)
            protected SempRequestType sempRequest;
            @XmlElement(name = "is-grouped")
            protected Object isGrouped;
            @XmlElement(name = "run-configuration", required = true)
            protected String runConfiguration;
            @XmlElement(required = true)
            protected DestinationType destination;
            @XmlElement(name = "topic-string-suffix", required = true)
            protected String topicStringSuffix;
            @XmlElement(name = "base-tag", required = true)
            protected String baseTag;
            @XmlElement(name = "object-tags")
            protected ObjectTagsType objectTags;
            @XmlElement(name = "min-semp-ver")
            protected String minSempVer;
            @XmlElement(name = "max-semp-ver")
            protected String maxSempVer;
            @XmlElement(name = "min-poll-interval-sec")
            protected Short minPollIntervalSec;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the sempRequest property.
             * 
             * @return
             *     possible object is
             *     {@link SempRequestType }
             *     
             */
            public SempRequestType getSempRequest() {
                return sempRequest;
            }

            /**
             * Sets the value of the sempRequest property.
             * 
             * @param value
             *     allowed object is
             *     {@link SempRequestType }
             *     
             */
            public void setSempRequest(SempRequestType value) {
                this.sempRequest = value;
            }

            /**
             * Gets the value of the isGrouped property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getIsGrouped() {
                return isGrouped;
            }

            /**
             * Sets the value of the isGrouped property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setIsGrouped(Object value) {
                this.isGrouped = value;
            }

            /**
             * Gets the value of the runConfiguration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunConfiguration() {
                return runConfiguration;
            }

            /**
             * Sets the value of the runConfiguration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunConfiguration(String value) {
                this.runConfiguration = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link DestinationType }
             *     
             */
            public DestinationType getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link DestinationType }
             *     
             */
            public void setDestination(DestinationType value) {
                this.destination = value;
            }

            /**
             * Gets the value of the topicStringSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTopicStringSuffix() {
                return topicStringSuffix;
            }

            /**
             * Sets the value of the topicStringSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTopicStringSuffix(String value) {
                this.topicStringSuffix = value;
            }

            /**
             * Gets the value of the baseTag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseTag() {
                return baseTag;
            }

            /**
             * Sets the value of the baseTag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseTag(String value) {
                this.baseTag = value;
            }

            /**
             * Gets the value of the objectTags property.
             * 
             * @return
             *     possible object is
             *     {@link ObjectTagsType }
             *     
             */
            public ObjectTagsType getObjectTags() {
                return objectTags;
            }

            /**
             * Sets the value of the objectTags property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObjectTagsType }
             *     
             */
            public void setObjectTags(ObjectTagsType value) {
                this.objectTags = value;
            }

            /**
             * Gets the value of the minSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMinSempVer() {
                return minSempVer;
            }

            /**
             * Sets the value of the minSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMinSempVer(String value) {
                this.minSempVer = value;
            }

            /**
             * Gets the value of the maxSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxSempVer() {
                return maxSempVer;
            }

            /**
             * Sets the value of the maxSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxSempVer(String value) {
                this.maxSempVer = value;
            }

            /**
             * Gets the value of the minPollIntervalSec property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getMinPollIntervalSec() {
                return minPollIntervalSec;
            }

            /**
             * Sets the value of the minPollIntervalSec property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setMinPollIntervalSec(Short value) {
                this.minPollIntervalSec = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="semp-request" type="{}semp-request-type"/>
         *         &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="destination" type="{}destination-type"/>
         *         &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
         *         &lt;element name="send-empty-message" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *         &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "description",
            "sempRequest",
            "runConfiguration",
            "destination",
            "topicStringSuffix",
            "baseTag",
            "objectTags",
            "sendEmptyMessage",
            "minSempVer",
            "maxSempVer",
            "minPollIntervalSec"
        })
        public static class SystemPoller {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "semp-request", required = true)
            protected SempRequestType sempRequest;
            @XmlElement(name = "run-configuration", required = true)
            protected String runConfiguration;
            @XmlElement(required = true)
            protected DestinationType destination;
            @XmlElement(name = "topic-string-suffix", required = true)
            protected String topicStringSuffix;
            @XmlElement(name = "base-tag", required = true)
            protected String baseTag;
            @XmlElement(name = "object-tags")
            protected ObjectTagsType objectTags;
            @XmlElement(name = "send-empty-message")
            protected Object sendEmptyMessage;
            @XmlElement(name = "min-semp-ver")
            protected String minSempVer;
            @XmlElement(name = "max-semp-ver")
            protected String maxSempVer;
            @XmlElement(name = "min-poll-interval-sec")
            protected Short minPollIntervalSec;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the sempRequest property.
             * 
             * @return
             *     possible object is
             *     {@link SempRequestType }
             *     
             */
            public SempRequestType getSempRequest() {
                return sempRequest;
            }

            /**
             * Sets the value of the sempRequest property.
             * 
             * @param value
             *     allowed object is
             *     {@link SempRequestType }
             *     
             */
            public void setSempRequest(SempRequestType value) {
                this.sempRequest = value;
            }

            /**
             * Gets the value of the runConfiguration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunConfiguration() {
                return runConfiguration;
            }

            /**
             * Sets the value of the runConfiguration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunConfiguration(String value) {
                this.runConfiguration = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link DestinationType }
             *     
             */
            public DestinationType getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link DestinationType }
             *     
             */
            public void setDestination(DestinationType value) {
                this.destination = value;
            }

            /**
             * Gets the value of the topicStringSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTopicStringSuffix() {
                return topicStringSuffix;
            }

            /**
             * Sets the value of the topicStringSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTopicStringSuffix(String value) {
                this.topicStringSuffix = value;
            }

            /**
             * Gets the value of the baseTag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseTag() {
                return baseTag;
            }

            /**
             * Sets the value of the baseTag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseTag(String value) {
                this.baseTag = value;
            }

            /**
             * Gets the value of the objectTags property.
             * 
             * @return
             *     possible object is
             *     {@link ObjectTagsType }
             *     
             */
            public ObjectTagsType getObjectTags() {
                return objectTags;
            }

            /**
             * Sets the value of the objectTags property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObjectTagsType }
             *     
             */
            public void setObjectTags(ObjectTagsType value) {
                this.objectTags = value;
            }

            /**
             * Gets the value of the sendEmptyMessage property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSendEmptyMessage() {
                return sendEmptyMessage;
            }

            /**
             * Sets the value of the sendEmptyMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSendEmptyMessage(Object value) {
                this.sendEmptyMessage = value;
            }

            /**
             * Gets the value of the minSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMinSempVer() {
                return minSempVer;
            }

            /**
             * Sets the value of the minSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMinSempVer(String value) {
                this.minSempVer = value;
            }

            /**
             * Gets the value of the maxSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxSempVer() {
                return maxSempVer;
            }

            /**
             * Sets the value of the maxSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxSempVer(String value) {
                this.maxSempVer = value;
            }

            /**
             * Gets the value of the minPollIntervalSec property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getMinPollIntervalSec() {
                return minPollIntervalSec;
            }

            /**
             * Sets the value of the minPollIntervalSec property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setMinPollIntervalSec(Short value) {
                this.minPollIntervalSec = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="semp-request" type="{}semp-request-type"/>
         *         &lt;element name="run-configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="destination" type="{}destination-type"/>
         *         &lt;element name="topic-string-suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="base-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vpn-name-tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="object-tags" type="{}object-tags-type" minOccurs="0"/>
         *         &lt;element name="min-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="max-semp-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="min-poll-interval-sec" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "description",
            "sempRequest",
            "runConfiguration",
            "destination",
            "topicStringSuffix",
            "baseTag",
            "vpnNameTag",
            "objectTags",
            "minSempVer",
            "maxSempVer",
            "minPollIntervalSec"
        })
        public static class VpnPoller {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "semp-request", required = true)
            protected SempRequestType sempRequest;
            @XmlElement(name = "run-configuration", required = true)
            protected String runConfiguration;
            @XmlElement(required = true)
            protected DestinationType destination;
            @XmlElement(name = "topic-string-suffix", required = true)
            protected String topicStringSuffix;
            @XmlElement(name = "base-tag", required = true)
            protected String baseTag;
            @XmlElement(name = "vpn-name-tag", required = true)
            protected String vpnNameTag;
            @XmlElement(name = "object-tags")
            protected ObjectTagsType objectTags;
            @XmlElement(name = "min-semp-ver")
            protected String minSempVer;
            @XmlElement(name = "max-semp-ver")
            protected String maxSempVer;
            @XmlElement(name = "min-poll-interval-sec")
            protected Short minPollIntervalSec;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the sempRequest property.
             * 
             * @return
             *     possible object is
             *     {@link SempRequestType }
             *     
             */
            public SempRequestType getSempRequest() {
                return sempRequest;
            }

            /**
             * Sets the value of the sempRequest property.
             * 
             * @param value
             *     allowed object is
             *     {@link SempRequestType }
             *     
             */
            public void setSempRequest(SempRequestType value) {
                this.sempRequest = value;
            }

            /**
             * Gets the value of the runConfiguration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunConfiguration() {
                return runConfiguration;
            }

            /**
             * Sets the value of the runConfiguration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunConfiguration(String value) {
                this.runConfiguration = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link DestinationType }
             *     
             */
            public DestinationType getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link DestinationType }
             *     
             */
            public void setDestination(DestinationType value) {
                this.destination = value;
            }

            /**
             * Gets the value of the topicStringSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTopicStringSuffix() {
                return topicStringSuffix;
            }

            /**
             * Sets the value of the topicStringSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTopicStringSuffix(String value) {
                this.topicStringSuffix = value;
            }

            /**
             * Gets the value of the baseTag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseTag() {
                return baseTag;
            }

            /**
             * Sets the value of the baseTag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseTag(String value) {
                this.baseTag = value;
            }

            /**
             * Gets the value of the vpnNameTag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVpnNameTag() {
                return vpnNameTag;
            }

            /**
             * Sets the value of the vpnNameTag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVpnNameTag(String value) {
                this.vpnNameTag = value;
            }

            /**
             * Gets the value of the objectTags property.
             * 
             * @return
             *     possible object is
             *     {@link ObjectTagsType }
             *     
             */
            public ObjectTagsType getObjectTags() {
                return objectTags;
            }

            /**
             * Sets the value of the objectTags property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObjectTagsType }
             *     
             */
            public void setObjectTags(ObjectTagsType value) {
                this.objectTags = value;
            }

            /**
             * Gets the value of the minSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMinSempVer() {
                return minSempVer;
            }

            /**
             * Sets the value of the minSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMinSempVer(String value) {
                this.minSempVer = value;
            }

            /**
             * Gets the value of the maxSempVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxSempVer() {
                return maxSempVer;
            }

            /**
             * Sets the value of the maxSempVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxSempVer(String value) {
                this.maxSempVer = value;
            }

            /**
             * Gets the value of the minPollIntervalSec property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getMinPollIntervalSec() {
                return minPollIntervalSec;
            }

            /**
             * Sets the value of the minPollIntervalSec property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setMinPollIntervalSec(Short value) {
                this.minPollIntervalSec = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="run-configuration" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="run-on-primary-when-active-standby" type="{}run-condition"/>
     *                   &lt;element name="run-on-backup-when-active-standby" type="{}run-condition"/>
     *                   &lt;element name="run-on-primary-when-active-active" type="{}run-condition"/>
     *                   &lt;element name="run-on-backup-when-active-active" type="{}run-condition"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runConfiguration"
    })
    public static class RunConfigurations {

        @XmlElement(name = "run-configuration", required = true)
        protected List<Config.RunConfigurations.RunConfiguration> runConfiguration;

        /**
         * Gets the value of the runConfiguration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runConfiguration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRunConfiguration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.RunConfigurations.RunConfiguration }
         * 
         * 
         */
        public List<Config.RunConfigurations.RunConfiguration> getRunConfiguration() {
            if (runConfiguration == null) {
                runConfiguration = new ArrayList<Config.RunConfigurations.RunConfiguration>();
            }
            return this.runConfiguration;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="run-on-primary-when-active-standby" type="{}run-condition"/>
         *         &lt;element name="run-on-backup-when-active-standby" type="{}run-condition"/>
         *         &lt;element name="run-on-primary-when-active-active" type="{}run-condition"/>
         *         &lt;element name="run-on-backup-when-active-active" type="{}run-condition"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "runOnPrimaryWhenActiveStandby",
            "runOnBackupWhenActiveStandby",
            "runOnPrimaryWhenActiveActive",
            "runOnBackupWhenActiveActive"
        })
        public static class RunConfiguration {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(name = "run-on-primary-when-active-standby", required = true)
            protected RunCondition runOnPrimaryWhenActiveStandby;
            @XmlElement(name = "run-on-backup-when-active-standby", required = true)
            protected RunCondition runOnBackupWhenActiveStandby;
            @XmlElement(name = "run-on-primary-when-active-active", required = true)
            protected RunCondition runOnPrimaryWhenActiveActive;
            @XmlElement(name = "run-on-backup-when-active-active", required = true)
            protected RunCondition runOnBackupWhenActiveActive;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the runOnPrimaryWhenActiveStandby property.
             * 
             * @return
             *     possible object is
             *     {@link RunCondition }
             *     
             */
            public RunCondition getRunOnPrimaryWhenActiveStandby() {
                return runOnPrimaryWhenActiveStandby;
            }

            /**
             * Sets the value of the runOnPrimaryWhenActiveStandby property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunCondition }
             *     
             */
            public void setRunOnPrimaryWhenActiveStandby(RunCondition value) {
                this.runOnPrimaryWhenActiveStandby = value;
            }

            /**
             * Gets the value of the runOnBackupWhenActiveStandby property.
             * 
             * @return
             *     possible object is
             *     {@link RunCondition }
             *     
             */
            public RunCondition getRunOnBackupWhenActiveStandby() {
                return runOnBackupWhenActiveStandby;
            }

            /**
             * Sets the value of the runOnBackupWhenActiveStandby property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunCondition }
             *     
             */
            public void setRunOnBackupWhenActiveStandby(RunCondition value) {
                this.runOnBackupWhenActiveStandby = value;
            }

            /**
             * Gets the value of the runOnPrimaryWhenActiveActive property.
             * 
             * @return
             *     possible object is
             *     {@link RunCondition }
             *     
             */
            public RunCondition getRunOnPrimaryWhenActiveActive() {
                return runOnPrimaryWhenActiveActive;
            }

            /**
             * Sets the value of the runOnPrimaryWhenActiveActive property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunCondition }
             *     
             */
            public void setRunOnPrimaryWhenActiveActive(RunCondition value) {
                this.runOnPrimaryWhenActiveActive = value;
            }

            /**
             * Gets the value of the runOnBackupWhenActiveActive property.
             * 
             * @return
             *     possible object is
             *     {@link RunCondition }
             *     
             */
            public RunCondition getRunOnBackupWhenActiveActive() {
                return runOnBackupWhenActiveActive;
            }

            /**
             * Sets the value of the runOnBackupWhenActiveActive property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunCondition }
             *     
             */
            public void setRunOnBackupWhenActiveActive(RunCondition value) {
                this.runOnBackupWhenActiveActive = value;
            }

        }

    }

}
