//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 04:30:34 PM BST 
//


package com.solace.psg.enterprisestats.statspump.config.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for run-condition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="run-condition">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PRIMARY_LOCAL_ACTIVE"/>
 *     &lt;enumeration value="BACKUP_LOCAL_ACTIVE"/>
 *     &lt;enumeration value="AD_ACTIVE"/>
 *     &lt;enumeration value="ALWAYS"/>
 *     &lt;enumeration value="NEVER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "run-condition")
@XmlEnum
public enum RunCondition {

    PRIMARY_LOCAL_ACTIVE,
    BACKUP_LOCAL_ACTIVE,
    AD_ACTIVE,
    ALWAYS,
    NEVER;

    public String value() {
        return name();
    }

    public static RunCondition fromValue(String v) {
        return valueOf(v);
    }

}
