//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 04:27:26 PM SGT 
//


package com.solace.psg.enterprisestats.statspump.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for appliance-semp-details-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="appliance-semp-details-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="semp-host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cli-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cli-password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secure" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "appliance-semp-details-type", propOrder = {
    "sempHost",
    "cliUsername",
    "cliPassword",
    "secure"
})
@XmlSeeAlso({
    com.solace.psg.enterprisestats.statspump.config.xml.Appliances.Appliance.Backup.class
})
public class ApplianceSempDetailsType {

    @XmlElement(name = "semp-host", required = true)
    protected String sempHost;
    @XmlElement(name = "cli-username", required = true)
    protected String cliUsername;
    @XmlElement(name = "cli-password", required = true)
    protected String cliPassword;
    protected Object secure;

    /**
     * Gets the value of the sempHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSempHost() {
        return sempHost;
    }

    /**
     * Sets the value of the sempHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSempHost(String value) {
        this.sempHost = value;
    }

    /**
     * Gets the value of the cliUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCliUsername() {
        return cliUsername;
    }

    /**
     * Sets the value of the cliUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCliUsername(String value) {
        this.cliUsername = value;
    }

    /**
     * Gets the value of the cliPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCliPassword() {
        return cliPassword;
    }

    /**
     * Sets the value of the cliPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCliPassword(String value) {
        this.cliPassword = value;
    }

    /**
     * Gets the value of the secure property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSecure() {
        return secure;
    }

    /**
     * Sets the value of the secure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSecure(Object value) {
        this.secure = value;
    }

}
