# PATH TO SOLACE C LIBRARIES #
SOLCLIENT_HOME=/root/solclient

# PATH TO PERL SCRIPT WHICH STARTS ADMIN LISTENER #
START_ADMIN_LISTENER=/usr/local/nagios/libexec/scripts/fireAdminListener.pl

# PATH TO ADMIN LISTENER BINARY #
ADMIN_LISTENER=/usr/local/nagios/libexec/WCFEventMonitor

# PATH TO DIR WITH VPN HOST CONFIG FILES FOR NAGIOS #
# AN ADMIN LISTENER PROCESS WILL BE STARTED FOR EACH FILE IN THIS DIR
VPN_DIR=/usr/local/nagios/etc/objects/solaceVpns/

# PATH TO DIR CONTAINING CREDENTIALS FOR CONNECTING TO ROUTERS #
CREDENTIALS_DIR=/home/nagios/config/
