//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 04:27:26 PM SGT 
//


package com.solace.psg.enterprisestats.statspump.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="publishTtl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="publishDmqEligible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="appliance" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="poller-group" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="primary" type="{}appliance-semp-details-type"/>
 *                   &lt;element name="backup" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}appliance-semp-details-type">
 *                           &lt;attribute name="mode" use="required" type="{}backup-mode-type" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="mgmt-msg-bus" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="local-mgmt-msg-bus" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="local-listener-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="local-listener-config" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="self-msg-bus" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;choice minOccurs="0">
 *                               &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="vpn-connection-acl-settings">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="vpn-exception" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                       &lt;/sequence>
 *                                       &lt;attribute name="default-action" use="required" type="{}exception-default-action-type" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                             &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publishTtl",
    "publishDmqEligible",
    "appliance"
})
@XmlRootElement(name = "appliances")
public class Appliances {

    protected long publishTtl;
    protected boolean publishDmqEligible;
    @XmlElement(required = true)
    protected List<Appliances.Appliance> appliance;

    /**
     * Gets the value of the publishTtl property.
     * 
     */
    public long getPublishTtl() {
        return publishTtl;
    }

    /**
     * Sets the value of the publishTtl property.
     * 
     */
    public void setPublishTtl(long value) {
        this.publishTtl = value;
    }

    /**
     * Gets the value of the publishDmqEligible property.
     * 
     */
    public boolean isPublishDmqEligible() {
        return publishDmqEligible;
    }

    /**
     * Sets the value of the publishDmqEligible property.
     * 
     */
    public void setPublishDmqEligible(boolean value) {
        this.publishDmqEligible = value;
    }

    /**
     * Gets the value of the appliance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Appliances.Appliance }
     * 
     * 
     */
    public List<Appliances.Appliance> getAppliance() {
        if (appliance == null) {
            appliance = new ArrayList<Appliances.Appliance>();
        }
        return this.appliance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="poller-group" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="primary" type="{}appliance-semp-details-type"/>
     *         &lt;element name="backup" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}appliance-semp-details-type">
     *                 &lt;attribute name="mode" use="required" type="{}backup-mode-type" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mgmt-msg-bus" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="local-mgmt-msg-bus" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="local-listener-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="local-listener-config" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="self-msg-bus" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;choice minOccurs="0">
     *                     &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="vpn-connection-acl-settings">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="vpn-exception" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                             &lt;/sequence>
     *                             &lt;attribute name="default-action" use="required" type="{}exception-default-action-type" />
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                   &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "pollerGroup",
        "primary",
        "backup",
        "mgmtMsgBus",
        "localMgmtMsgBus",
        "selfMsgBus"
    })
    public static class Appliance {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "poller-group")
        protected List<String> pollerGroup;
        @XmlElement(required = true)
        protected ApplianceSempDetailsType primary;
        protected Appliances.Appliance.Backup backup;
        @XmlElement(name = "mgmt-msg-bus")
        protected List<Appliances.Appliance.MgmtMsgBus> mgmtMsgBus;
        @XmlElement(name = "local-mgmt-msg-bus")
        protected List<Appliances.Appliance.LocalMgmtMsgBus> localMgmtMsgBus;
        @XmlElement(name = "self-msg-bus")
        protected List<Appliances.Appliance.SelfMsgBus> selfMsgBus;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the pollerGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pollerGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPollerGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPollerGroup() {
            if (pollerGroup == null) {
                pollerGroup = new ArrayList<String>();
            }
            return this.pollerGroup;
        }

        /**
         * Gets the value of the primary property.
         * 
         * @return
         *     possible object is
         *     {@link ApplianceSempDetailsType }
         *     
         */
        public ApplianceSempDetailsType getPrimary() {
            return primary;
        }

        /**
         * Sets the value of the primary property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplianceSempDetailsType }
         *     
         */
        public void setPrimary(ApplianceSempDetailsType value) {
            this.primary = value;
        }

        /**
         * Gets the value of the backup property.
         * 
         * @return
         *     possible object is
         *     {@link Appliances.Appliance.Backup }
         *     
         */
        public Appliances.Appliance.Backup getBackup() {
            return backup;
        }

        /**
         * Sets the value of the backup property.
         * 
         * @param value
         *     allowed object is
         *     {@link Appliances.Appliance.Backup }
         *     
         */
        public void setBackup(Appliances.Appliance.Backup value) {
            this.backup = value;
        }

        /**
         * Gets the value of the mgmtMsgBus property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mgmtMsgBus property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMgmtMsgBus().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Appliances.Appliance.MgmtMsgBus }
         * 
         * 
         */
        public List<Appliances.Appliance.MgmtMsgBus> getMgmtMsgBus() {
            if (mgmtMsgBus == null) {
                mgmtMsgBus = new ArrayList<Appliances.Appliance.MgmtMsgBus>();
            }
            return this.mgmtMsgBus;
        }

        /**
         * Gets the value of the localMgmtMsgBus property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the localMgmtMsgBus property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLocalMgmtMsgBus().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Appliances.Appliance.LocalMgmtMsgBus }
         * 
         * 
         */
        public List<Appliances.Appliance.LocalMgmtMsgBus> getLocalMgmtMsgBus() {
            if (localMgmtMsgBus == null) {
                localMgmtMsgBus = new ArrayList<Appliances.Appliance.LocalMgmtMsgBus>();
            }
            return this.localMgmtMsgBus;
        }

        /**
         * Gets the value of the selfMsgBus property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the selfMsgBus property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSelfMsgBus().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Appliances.Appliance.SelfMsgBus }
         * 
         * 
         */
        public List<Appliances.Appliance.SelfMsgBus> getSelfMsgBus() {
            if (selfMsgBus == null) {
                selfMsgBus = new ArrayList<Appliances.Appliance.SelfMsgBus>();
            }
            return this.selfMsgBus;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}appliance-semp-details-type">
         *       &lt;attribute name="mode" use="required" type="{}backup-mode-type" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Backup
            extends ApplianceSempDetailsType
        {

            @XmlAttribute(name = "mode", required = true)
            protected BackupModeType mode;

            /**
             * Gets the value of the mode property.
             * 
             * @return
             *     possible object is
             *     {@link BackupModeType }
             *     
             */
            public BackupModeType getMode() {
                return mode;
            }

            /**
             * Sets the value of the mode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BackupModeType }
             *     
             */
            public void setMode(BackupModeType value) {
                this.mode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="local-listener-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="local-listener-config" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "host",
            "localListenerClass",
            "localListenerConfig",
            "containerFactoryClass"
        })
        public static class LocalMgmtMsgBus {

            protected String host;
            @XmlElement(name = "local-listener-class", required = true)
            protected String localListenerClass;
            @XmlElement(name = "local-listener-config", required = true)
            protected String localListenerConfig;
            @XmlElement(name = "container-factory-class", required = true)
            protected String containerFactoryClass;

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the localListenerClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalListenerClass() {
                return localListenerClass;
            }

            /**
             * Sets the value of the localListenerClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalListenerClass(String value) {
                this.localListenerClass = value;
            }

            /**
             * Gets the value of the localListenerConfig property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalListenerConfig() {
                return localListenerConfig;
            }

            /**
             * Sets the value of the localListenerConfig property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalListenerConfig(String value) {
                this.localListenerConfig = value;
            }

            /**
             * Gets the value of the containerFactoryClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContainerFactoryClass() {
                return containerFactoryClass;
            }

            /**
             * Sets the value of the containerFactoryClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContainerFactoryClass(String value) {
                this.containerFactoryClass = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "host",
            "vpn",
            "clientUsername",
            "password",
            "containerFactoryClass"
        })
        public static class MgmtMsgBus {

            @XmlElement(required = true)
            protected String host;
            @XmlElement(required = true)
            protected String vpn;
            @XmlElement(name = "client-username", required = true)
            protected String clientUsername;
            protected String password;
            @XmlElement(name = "container-factory-class", required = true)
            protected String containerFactoryClass;

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the vpn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVpn() {
                return vpn;
            }

            /**
             * Sets the value of the vpn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVpn(String value) {
                this.vpn = value;
            }

            /**
             * Gets the value of the clientUsername property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientUsername() {
                return clientUsername;
            }

            /**
             * Sets the value of the clientUsername property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientUsername(String value) {
                this.clientUsername = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the containerFactoryClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContainerFactoryClass() {
                return containerFactoryClass;
            }

            /**
             * Sets the value of the containerFactoryClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContainerFactoryClass(String value) {
                this.containerFactoryClass = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;choice minOccurs="0">
         *           &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *           &lt;element name="vpn-connection-acl-settings">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="vpn-exception" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                   &lt;/sequence>
         *                   &lt;attribute name="default-action" use="required" type="{}exception-default-action-type" />
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *         &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="container-factory-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "host",
            "vpn",
            "vpnConnectionAclSettings",
            "clientUsername",
            "password",
            "containerFactoryClass"
        })
        public static class SelfMsgBus {

            @XmlElement(required = true)
            protected String host;
            protected String vpn;
            @XmlElement(name = "vpn-connection-acl-settings")
            protected Appliances.Appliance.SelfMsgBus.VpnConnectionAclSettings vpnConnectionAclSettings;
            @XmlElement(name = "client-username", required = true)
            protected String clientUsername;
            protected String password;
            @XmlElement(name = "container-factory-class", required = true)
            protected String containerFactoryClass;

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the vpn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVpn() {
                return vpn;
            }

            /**
             * Sets the value of the vpn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVpn(String value) {
                this.vpn = value;
            }

            /**
             * Gets the value of the vpnConnectionAclSettings property.
             * 
             * @return
             *     possible object is
             *     {@link Appliances.Appliance.SelfMsgBus.VpnConnectionAclSettings }
             *     
             */
            public Appliances.Appliance.SelfMsgBus.VpnConnectionAclSettings getVpnConnectionAclSettings() {
                return vpnConnectionAclSettings;
            }

            /**
             * Sets the value of the vpnConnectionAclSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link Appliances.Appliance.SelfMsgBus.VpnConnectionAclSettings }
             *     
             */
            public void setVpnConnectionAclSettings(Appliances.Appliance.SelfMsgBus.VpnConnectionAclSettings value) {
                this.vpnConnectionAclSettings = value;
            }

            /**
             * Gets the value of the clientUsername property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientUsername() {
                return clientUsername;
            }

            /**
             * Sets the value of the clientUsername property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientUsername(String value) {
                this.clientUsername = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the containerFactoryClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContainerFactoryClass() {
                return containerFactoryClass;
            }

            /**
             * Sets the value of the containerFactoryClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContainerFactoryClass(String value) {
                this.containerFactoryClass = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="vpn-exception" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *       &lt;attribute name="default-action" use="required" type="{}exception-default-action-type" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "vpnException"
            })
            public static class VpnConnectionAclSettings {

                @XmlElement(name = "vpn-exception", required = true)
                protected List<String> vpnException;
                @XmlAttribute(name = "default-action", required = true)
                protected ExceptionDefaultActionType defaultAction;

                /**
                 * Gets the value of the vpnException property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the vpnException property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getVpnException().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getVpnException() {
                    if (vpnException == null) {
                        vpnException = new ArrayList<String>();
                    }
                    return this.vpnException;
                }

                /**
                 * Gets the value of the defaultAction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ExceptionDefaultActionType }
                 *     
                 */
                public ExceptionDefaultActionType getDefaultAction() {
                    return defaultAction;
                }

                /**
                 * Sets the value of the defaultAction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ExceptionDefaultActionType }
                 *     
                 */
                public void setDefaultAction(ExceptionDefaultActionType value) {
                    this.defaultAction = value;
                }

            }

        }

    }

}
